print("hello world")
print("howdy, y'all!")
print("i like typing this.")
print("printing....Yay!!!")
# what the fudge
print("I will now count my chickens.")
print("Hens", 25  + 30 / 6)
print("Roosters: ", 100 - 25 * 3 % 4)
print(3 + 2 + 1 -5 + 4 % 2 -1 / 4 + 6)
print("I will now count my brain cells:")
print("brain cells --->", 100 - 25 * 3 % 4)
print("now i will count my subscribers:")
print("subscribers --->", 3 + 2 + 1 - 5 + 4 % 2 -1 / 4 + 6)
print("is it true that 3 + 2 < 5 - 7")
print(3 + 2 < 5 - 7)